language: python

python:
  - 3.6.7

services: postgresql

env:
  - DJANGO=2.1.5

before_install:
  - export DJANGO_SETTINGS_MODULE=crawler.settings
  - export PYTHONPATH=$HOME/builds/guilehm/crawler
  - export PIP_USE_MIRRORS=true

install:
  - pip install pipenv
  - pipenv install --dev
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres

script:
  - python manage.py test
  - isort --check-only
  - flake8
  - pytest -v
