language: python

python:
  - 3.6.7

services:
  - docker

env:
  - DJANGO=2.1.5

before_install:
  - export DJANGO_SETTINGS_MODULE=crawler.settings
  - export PYTHONPATH=$HOME/builds/guilehm/crawler
  - export PIP_USE_MIRRORS=true

install:
  - pip install pipenv
  - pipenv install --dev
  - docker-compose -v
  - docker -v

before_script:
  - python manage.py migrate

script:
  - pipenv run make detect-migrations
  - pipenv run make test
